# Generated by Django 5.2.2 on 2025-06-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=12),
        ),
    ]
