# Generated by Django 5.2.3 on 2025-06-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_plan_amount_alter_plan_roi_alter_plan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='eth',
            field=models.DecimalField(decimal_places=7, default=20.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='solona',
            field=models.DecimalField(decimal_places=5, default=20.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ton',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=12),
        ),
    ]
