# Generated by Django 5.2.3 on 2025-06-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wallet_eth_wallet_solona_wallet_ton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='eth',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='solona',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ton',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
