# Generated by Django 5.2.3 on 2025-06-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_wallet_eth_alter_wallet_solona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='solona',
            new_name='solana',
        ),
    ]
